### PR TITLE
Modified readme file

### PR DESCRIPTION
**Pull request by chaitanya-pandeswara**
Modified the readme file.

Please Review.

### CODE REVIEW

**Comment by pandeswara29** [comment]
More content needed.

**Comment by chaitanya-pandeswara** [comment]
Ok, will update and let you know.

**Comment by chaitanya-pandeswara** [comment]
Modified, kindly review.

**Comment by pandeswara29** [comment]
Looking good. you can merge.

**Comment by chaitanya-pandeswara** [comment]
Added few more changes.

Kindly Review

**Comment by pandeswara29** [comment]
Looking Great. Submit the changes to master.

**Pull request merged**
